# kafkactl configuration for Kong Event Gateway (KEG)
# This configuration provides contexts for connecting to operations, analytics, and partner virtual clusters

contexts:
  # Operations context - connects via SNI routing with topic prefix 'operations-'
  operations:
    brokers:
      - bootstrap.operations.127-0-0-1.sslip.io:9094
    tls:
      enabled: true
      insecure: true # Set to false in production with proper CA
    sasl:
      enabled: false # Anonymous authentication as configured in KEG
    clientID: kafkactl-operations
    requestTimeout: 10s
    retryBackoff: 100ms

  # Analytics context - connects via SNI routing with topic prefix 'analytics-'
  analytics:
    brokers:
      - bootstrap.analytics.127-0-0-1.sslip.io:9094
    tls:
      enabled: true
      insecure: true # Set to false in production with proper CA
    sasl:
      enabled: false # Anonymous authentication as configured in KEG
    clientID: kafkactl-analytics
    requestTimeout: 10s
    retryBackoff: 100ms

  # Partner context - connects via SNI routing with topic prefix 'partner-'
  partners:
    brokers:
      - bootstrap.partners.127-0-0-1.sslip.io:9094
    tls:
      enabled: true
      insecure: true # Set to false in production with proper CA
    sasl:
      enabled: false # Anonymous authentication as configured in KEG
    clientID: kafkactl-partner
    requestTimeout: 10s
    retryBackoff: 100ms

  # Direct Kafka cluster access (for admin operations)
  # Requires port-forwarding: kubectl port-forward svc/my-cluster-kafka-bootstrap 9092:9092 -n kafka
  kafka-direct:
    brokers:
      - localhost:9092
    tls:
      enabled: false
    sasl:
      enabled: false
    clientID: kafkactl-admin
    requestTimeout: 10s
    retryBackoff: 100ms

# Default context
current-context: operations

# Global settings
defaultPartitions: 3
defaultReplicationFactor: 3
