apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  otel-collector-config.yaml: |
    receivers:
      otlp/keg:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
      prometheus/keg:
        config:
          scrape_configs:
            - job_name: kong
              scrape_interval: 5s
              static_configs:
                - targets: ['kong-event-gateway.keg.svc.cluster.local:8080']

    processors:
      batch: {}

    extensions:
      health_check: {}

    exporters:
      otlp/jaeger:
        endpoint: jaeger.observability.svc.cluster.local:4317
        tls:
          insecure: true
      prometheusremotewrite:
        endpoint: http://prometheus.observability.svc.cluster.local:9090/prometheus/api/v1/write
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp/keg]
          processors: [batch]
          exporters: [otlp/jaeger]
        metrics:
          receivers: [prometheus/keg]
          processors: [batch]
          exporters: [prometheusremotewrite]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:latest
          args: ["--config=/etc/otel-collector-config.yaml"]
          volumeMounts:
            - name: otel-collector-config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
          ports:
            - containerPort: 4317
              name: otlp-grpc
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 500m
      volumes:
        - name: otel-collector-config
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app: otel-collector
spec:
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
  selector:
    app: otel-collector
  type: ClusterIP
